# Generated by Django 5.0.3 on 2024-06-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineslog',
            name='account',
            field=models.ForeignKey(default='11140                                        ', on_delete=django.db.models.deletion.CASCADE, to='budgets.accounts'),
        ),
    ]
