# Generated by Django 5.0.3 on 2024-08-13 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgetlineslog_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetvariations',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2024', max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('netperd1', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd2', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd3', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd4', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd5', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd6', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd7', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd8', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd9', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd10', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd11', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netperd12', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('account', models.ForeignKey(default='11140                                        ', on_delete=django.db.models.deletion.CASCADE, to='budgets.accounts')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
