# Generated by Django 5.0.3 on 2024-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetvariations_year_accountchanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4)),
            ],
        ),
    ]
