# Generated by Django 5.0.3 on 2024-08-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_financialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgettotals')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.department')),
            ],
        ),
    ]
