# Generated by Django 5.0.3 on 2024-08-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='budget',
        ),
    ]
