# Generated by Django 5.0.3 on 2024-08-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_remove_group_department_budgettotals_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.department'),
        ),
    ]
