# Generated by Django 5.0.3 on 2024-08-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_group_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgettotals',
            name='group',
        ),
    ]
