# Generated by Django 5.0.3 on 2024-08-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_remove_budgettotals_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.accounts'),
        ),
    ]
