# Generated by Django 5.0.3 on 2024-08-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_group_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlines',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.group'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='account',
        ),
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ManyToManyField(to='budgets.accounts'),
        ),
    ]
