# Generated by Django 5.0.3 on 2024-08-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_budgetlines_group_remove_group_account_group_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='account',
        ),
        migrations.AddField(
            model_name='accounts',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.group'),
        ),
    ]
