# Generated by Django 5.0.3 on 2024-08-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_remove_group_account_accounts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='budgets.group'),
        ),
    ]
