# Generated by Django 5.0.3 on 2024-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_group_parent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd_changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='previous_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
