# Generated by Django 5.0.3 on 2024-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_budgetlineslog_netperd_changes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetlineslog',
            old_name='previous_total',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='budgetlineslog',
            name='budget_set',
        ),
        migrations.RemoveField(
            model_name='budgetlineslog',
            name='department',
        ),
        migrations.RemoveField(
            model_name='budgetlineslog',
            name='netperd_changes',
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd1',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd10',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd11',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd12',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd2',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd3',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd4',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd5',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd6',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd7',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd8',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineslog',
            name='netperd9',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
