# Generated by Django 5.0.3 on 2024-09-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_rename_previous_total_budgetlineslog_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineslog',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.department'),
        ),
    ]
