# Generated by Django 5.0.3 on 2024-10-06 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_budgetlineslog_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLinesLogVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('item_description', models.CharField(max_length=255, null=True)),
                ('period', models.CharField(max_length=50)),
                ('account', models.ForeignKey(default='11140                                        ', on_delete=django.db.models.deletion.CASCADE, to='budgets.accounts')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
