# Generated by Django 5.0.3 on 2024-10-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_budgetlineslogvariations_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='department',
        ),
        migrations.AddField(
            model_name='changelog',
            name='year',
            field=models.CharField(default='2024', max_length=4, null=True),
        ),
    ]
