# Generated by Django 5.0.3 on 2025-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_remove_changelog_department_changelog_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineslogvariations',
            name='comment',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
